---
defaults:
 -
   scope:
     path: "detective-is-already-dead.html"
     type: "post"
   values:
     layout: "default"
     limit_posts: 0
     future: false
     unpublished: false
     permalink: date
     paginate_path: /page:num
     timezone: null
---
